### ISSUE TITLE
Better quality MP3s are available via SoundCloud

### ISSUE THREAD

**Issue by StevenMaude** [jsdf/rinsefm-feed#1]
A heads up more than an issue really. I started working on a similar project to scrape the Rinse website, then noticed that the higher bitrate MP3s on [SoundCloud](https://soundcloud.com/rinsefm) are higher quality. Your project looks pretty neat, by the way!

**Comment by jsdf** [comment]
Cool, I'll look into taking that data in somehow. Possibly in a separate project (as this one is fairly coupled to the scrape data)

Cheers for that

**Comment by rtsao** [comment]
@StevenMaude You might find this useful:

https://github.com/L33T-KR3W/soundcasts-server
http://api.soundcasts.net/soundcast.xml?title=Rinse%20FM&userId=rinsefm&regexString=podcast

**Comment by StevenMaude** [comment]
Closing this since it's no longer possible: Rinse FM's [SoundCloud profile was taken down on Friday](https://twitter.com/RinseFM/status/885900146915016705).
